version: 2

models:
  - name: dim_aircraft
    description: "dba class project"
    columns:
      - name: idaircraft_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

models:
  - name: dim_airport
    description: "dba class project"
    columns:
      - name: airport_code
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

